package org.usfirst.frc5577.GearsBot.commands;

import org.usfirst.frc5577.GearsBot.Robot;

import edu.wpi.first.wpilibj.command.Command;

public class BackUp extends Command {
	double speed = 0.75;
    double time = 1.5;
	
	public  BackUp() {
  	  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
      requires(Robot.driveTrain);

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		 
  }
  
  public BackUp(double speed) {
  	this();
  	this.speed = speed;
  }
  
  public BackUp(double speed, double time) {
  	this(speed);
  	this.time = time;
  }
  // Called just before this Command runs the first time
  protected void initialize() {
	  setTimeout(time); //Or change back to 5 if something goes wrong
	  }

  // Called repeatedly when this Command is scheduled to run
  protected void execute() {
  	Robot.driveTrain.driveTrainBackward(speed);
  }

  // Make this return true when this Command no longer needs to run execute()
  protected boolean isFinished() {
      return isTimedOut(); 
  }

  // Called once after isFinished returns true
  protected void end() {
  	//Robot.climbingArm.disable();
  	
  	Robot.driveTrain.stop(); 
  }

  // Called when another command which requires one or more of the same
  // subsystems is scheduled to run
  protected void interrupted() {
  	end();
  }
}


